version: "3.9"

volumes:
  mongodb_volume:

services:
  web_service:
    build: .
    restart: always
    ports:
      - 49165:80
      #- 49166:443
      

  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - mongodb_volume:/data/db
    restart: always
    ports:
      - 27017:27017

  